[workspace]
resolver = "2"

members = [
    "dlprotoc-example",
    "protobuf-src-example",
]

[workspace.lints.clippy]
nursery = "deny"
pedantic = "deny"
style = "deny"
cargo = "deny"

[workspace.dependencies]
dlprotoc = "0"
prost = "0"
prost-types = "0"
prost-build = "0"
protobuf-src = "2"
