[package]
name = "protobuf-src-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
protobuf-src = { workspace = true }
