[package]
name = "dlprotoc-example"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }

[build-dependencies]
dlprotoc = { workspace = true }
prost-build = { workspace = true }
